name: docker-stage-latest
on:
  push:
    branches:
      - "development"

jobs:
  build-and-push-app:
    name: Build & Push App
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_REPOSITORY }}
          username: ${{ secrets.ARTIFACTORY_TRAIN_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_TRAIN_PASSWORD }}

      - name: Build and push app latest stage version
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/app.dockerfile
          target: prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_NAMESPACE }}:latest-stage
            ${{ secrets.ARTIFACTORY_REPOSITORY }}/${{ secrets.DOCKERHUB_NAMESPACE }}:latest-stage
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_NAMESPACE }}:latest-stage
          cache-to: type=inline

  build-and-push-worker:
    name: Build & Push Worker
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_REPOSITORY }}
          username: ${{ secrets.ARTIFACTORY_TRAIN_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_TRAIN_PASSWORD }}

      - name: Build and push worker latest stage version
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/worker.dockerfile
          target: prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_NAMESPACE }}:worker-latest-stage
            ${{ secrets.ARTIFACTORY_REPOSITORY }}/${{ secrets.DOCKERHUB_NAMESPACE }}:worker-latest-stage
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_NAMESPACE }}:worker-latest-stage
          cache-to: type=inline

  update-description:
    name: Update Description
    runs-on: ubuntu-latest
    needs: [build-and-push-app, build-and-push-worker]
    if: success()
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_NAMESPACE }}
